"""Create tables

Revision ID: 68c90b2d23b7
Revises: 
Create Date: 2026-01-11 23:16:57.036552

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import VECTOR
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c90b2d23b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
                    sa.Column('document_id', sa.UUID(), nullable=False),
                    sa.Column('source', sa.String(), nullable=False),
                    sa.Column('source_type', sa.String(
                        length=50), nullable=True),
                    sa.Column('checksum', sa.String(
                        length=64), nullable=False),
                    sa.Column('doc_metadata', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('document_id'),
                    sa.UniqueConstraint('checksum')
                    )
    op.create_table('chunks',
                    sa.Column('chunk_id', sa.UUID(), nullable=False),
                    sa.Column('document_id', sa.UUID(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('content_hash', sa.String(
                        length=64), nullable=False),
                    sa.Column('token_count', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['document_id'], ['documents.document_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('chunk_id'),
                    sa.UniqueConstraint('content_hash')
                    )
    op.create_index(op.f('ix_chunks_document_id'),
                    'chunks', ['document_id'], unique=False)
    op.create_table('embeddings',
                    sa.Column('chunk_id', sa.UUID(), nullable=False),
                    sa.Column('embedding', VECTOR(dim=1536), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['chunk_id'], ['chunks.chunk_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('chunk_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###
